### PR TITLE
Enable connecting over ipv6

### PR DESCRIPTION
**Pull request by sasikumar87**
Changes to enable connecting over ipv6

### CODE REVIEW

**Comment by maltoe** [comment]
Hey @sasikumar87 

may I ask what do you need this for?

**Comment by sasikumar87** [comment]
Hi @maltoe, I am trying to deploy chrome on a fly.io machine in private mode. Fly machine's ipv4 is always public. To make it private, I must use IPv6.
Ref : https://fly.io/docs/networking/app-services/#private-flycast-apps-2

Though I tested it further and found `websokex` also needs change at `:gen_tcp.connect` to make websockets connect over ipv6. https://github.com/Azolo/websockex/blob/v0.4.3/lib/websockex/conn.ex#L156 

So the changes in this PR alone is not sufficient without websockex changes.

**Comment by sasikumar87** [comment]
I'll close this for now, as websockex also needs change.

**Comment by walter** [comment]
@sasikumar87 I'm not seeing a PR or issue on websockex with the required change for ipv6. Is there something in the works to support it?

**Comment by sasikumar87** [comment]
@walter I just raised an issue in websockex https://github.com/Azolo/websockex/issues/131 .

**Pull request closed without merging**
