### PR TITLE
Replace plug_cowboy with bandit as integration test server.

### PR DESCRIPTION
**Pull request by maltoe**
This was easier than thought. Payback day.

### CODE REVIEW

**Comment by andreasknoepfle** [comment]
🤷 I don't know. I'd leave it there, since it can happen with any elixir dep that depends on an erlang package.

**Comment by andreasknoepfle** [comment]
No even sure that it is worth it switching to bandit, now that we know what is going on

**Comment by maltoe** [comment]
> No even sure that it is worth it switching to bandit, now that we know what is going on

I know... but I figured why not try something new for a change.

**Review by andreasknoepfle — APPROVED** [review]

**Comment by nickgnd** [comment]
Living on the edge 🚀

**Pull request merged**
