### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S deps -L warmup,ot`

### CODE REVIEW

**Comment by andreasknoepfle** [comment]
@maltoe maybe we should switch to action at some point. I have no clue, why CircleCI keeps forgetting out configs...

**Review by andreasknoepfle — APPROVED** [review]

**Review by maltoe — APPROVED** [review]

**Comment by maltoe** [comment]
> @maltoe maybe we should switch to action at some point. I have no clue, why CircleCI keeps forgetting out configs...

Agree. Not even too difficult anymore, IMO

- [ ] Find out why this one test case always fails ([example run](https://github.com/bitcrowd/chromic_pdf/actions/runs/3704537014/jobs/6277273477))
- [ ] Find a way to install verapdf & ZUV without doing it manually every time (or ditch ZUV). Is it possible to use docker images in actions?

**Comment by maltoe** [comment]
Also, thanks @kianmeng 

@andreasknoepfle we should also make `codespell` part of our pipelines

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
