### PR TITLE
[120] Explicit connection lost error and helpful sandbox docs.

### PR DESCRIPTION
**Pull request by maltoe**
* When Chrome dies at startup, display a helpful error message.
* Improve sandbox docs, mention Docker & seccomp.

Addresses #120.

### CODE REVIEW

**Review by andreasknoepfle — APPROVED** [review]
Looks awesome 💚

**Comment by cigzigwon** [comment]
I'm on Fedora 36 trying to figure out why this won't work on our server-side. I ran a test to generate a PDF from the CLI via google-chrome and that works. I also touched the interface for the --remote-debugging-pipe option via the input/output buffers and that seems to respond as well. It doesn't really matter what options i pass.... All I see is this default connection lost error. The output ALWAYS gets discarded. Any pointers to this configuration? Is there something I need to do with rights/perms or w/NimblePool config? I'm not sure what to do.

**Comment by maltoe** [comment]
Hi @cigzigwon 

> Is there something I need to do with rights/perms or w/NimblePool config?

No and no.

> It doesn't really matter what options i pass.... All I see is this default connection lost error. The output ALWAYS gets discarded.

You mean the Chrome output, yes? Are you running with the `discard_stderr: false` option? In your supervisor where you add ChromicPDF, you need to add it to the options

```elixir
children =[
  ...
  {ChromicPDF, discard_stderr: false}
]
...
```

If you have `elixir` installed on your server, you could also run a script to try it outside your actual application

```
#!/usr/bin/env elixir

Mix.install([{:chromic_pdf, "1.3.0"}])
ChromicPDF.start_link(discard_stderr: false)
{:ok, _} = ChromicPDF.print_to_pdf({:html, "test"})
```

Not sure if this helps.

If you can't figure it out and need more help, please open a ticket for it :purple_heart:

**Comment by cigzigwon** [comment]
Theres no Chrome errors and you can see I supplied a custom config. We don't have `elixir` installed in PROD due to it being a distillery release package.

`2022-11-04 07:30:29.557 [error] GenServer #PID<0.2596.0> terminating
** (ChromicPDF.Connection.ConnectionLostError) Chrome has stopped or was terminated by an external program.
If this happened while you were printing a PDF, this may be a problem with Chrome itelf.
If this happens at startup and you are running inside a Docker container with a Linux-based
image, please see the "Chrome Sandbox in Docker containers" section of the documentation.
Either way, to see Chrome's error output, configure ChromicPDF with the option
    discard_stderr: false
    (chromic_pdf 1.2.2) lib/chromic_pdf/pdf/connection.ex:96: ChromicPDF.Connection.terminate/2
    (stdlib 3.15) gen_server.erl:733: :gen_server.try_terminate/3
    (stdlib 3.15) gen_server.erl:918: :gen_server.terminate/10
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #Port<0.71>, :normal}
2022-11-04 07:30:29.561 application=phoenix [error] exited in: NimblePool.checkout(#PID<0.2597.0>)
    ** (EXIT) shutdown`

**Pull request merged**
